### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by luongvo** [RkNaing/nimble_survey#1]
Hi @RkNaing (Zaw Myo Naing) 👋 , thank you for your effort on the code submission. I am Lucas, Technical Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by RkNaing** [comment]
Hello @luongvo (Lucas) 👋, nice to e-meet you. Got it. 😀  Sure, I will be responsive. ✌️

**Comment by luongvo** [comment]
Hi there 👋 First of all, you did well to include the necessary features & requirements.
- Overall, cleanly implemented architecture, with Compose and some tests added.
- Detailed README instruction & demonstration. Especially a module graph explanation in mermaid, we really appreciated your effort.
- Caching with Room.


There are also some concerns that we would like to understand your thoughts and what you will do to improve. Please find them via issues 👋  

We will re-check and submit the review by this Thursday afternoon. Please take your time to go through these issues and share your thoughts (also with your code updates if possible). Thank you for your understanding and collaboration 😇

**Comment by RkNaing** [comment]
Hi @luongvo , Thank you for your feedback and review. Yep, certainly, I will work on the issues. 😀

**Comment by RkNaing** [comment]
Hi @luongvo , I have worked on your feedbacks and suggestions. Please kindly let me know if there is anything further you would like to address. ✌️
