### ISSUE TITLE
Parsing JSON:API manually

### ISSUE THREAD

**Issue by luongvo** [RkNaing/nimble_survey#2]
Hi, I'm not sure if have you heard of and implemented [JSON:API](https://jsonapi.org/) parser before. Our provided API follows [JSON:API](https://jsonapi.org/) specification and your current API models look a bit manual to parse it (see [here](https://github.com/RkNaing/nimble_survey/blob/master/features/survey/data/src/main/java/com/nimble/zawmyonaing/survey/data/remote/models/SurveyDto.kt)). 
It would be great if you could propose and apply a mechanism or library that can help us parse these response models automatically and is much simpler 💭

**Comment by RkNaing** [comment]
Hi, @luongvo , I have updated the source code and merged with [this pull request](https://github.com/RkNaing/nimble_survey/pull/7). I have also described the details in the PR's description. Please kindly let me know if you any further suggestion/comment. Thanks. ✌️
