### ISSUE TITLE
Some issues regarding the DI

### ISSUE THREAD

**Issue by luongvo** [RkNaing/nimble_survey#4]
According to what I see from your implementation, everything seems to be `Singleton` (e.g: [SurveyRepository](https://github.com/RkNaing/nimble_survey/blob/master/features/survey/data/src/main/java/com/nimble/zawmyonaing/survey/data/di/RepositoriesModule.kt)). 
- Should we keep all Repository as Singleton? Could you please explain why and your way to improve it? 
- Are there any other components that could be refactored as well?

**Comment by RkNaing** [comment]
Hi @luongvo , 

Yep, you are right. As these repositories are used in `ViewModel`s, It is more appropriate to keep them in the `ViewModelComponent` rather than the `SingletonComponent`. I have update the code and merged it in this [pull request](https://github.com/RkNaing/nimble_survey/pull/12).
