### ISSUE TITLE
No production (release) build flavor

### ISSUE THREAD

**Issue by luongvo** [RkNaing/nimble_survey#5]
Can we enable the production (release) flavor? What's your proposed config for the "release" flavor?

<img width="402" alt="image" src="https://github.com/RkNaing/nimble_survey/assets/16315358/99e75214-193f-4c40-845d-d85e20bef78f">

**Comment by RkNaing** [comment]
Hi, @luongvo , I have added the production flavor and merged with this [pull request](https://github.com/RkNaing/nimble_survey/pull/8) . Please kindly see the details in the PR's description. Please kindly let me know if you any further suggestion/comment. Thanks. ✌️
